#include "driver/gpio.h"
#include "driver/i2c.h"
#include "esp_err.h"
#include "esp_log.h"
#include "freertos/task.h"

#include "sdkconfig.h" // generated by "make menuconfig"

#include "bme280.h"

#define SDA_PIN GPIO_NUM_21
#define SCL_PIN GPIO_NUM_22

#define TAG_BME280 "BME280"

#define I2C_MASTER_ACK 0
#define I2C_MASTER_NACK 1

void i2c_master_init()
{
	i2c_config_t i2c_config = {
		.mode = I2C_MODE_MASTER,
		.sda_io_num = SDA_PIN,
		.scl_io_num = SCL_PIN,
		.sda_pullup_en = GPIO_PULLUP_ENABLE,
		.scl_pullup_en = GPIO_PULLUP_ENABLE,
		.master.clk_speed = 1000000
	};
	i2c_param_config(I2C_NUM_0, &i2c_config);
	i2c_driver_install(I2C_NUM_0, I2C_MODE_MASTER, 0, 0, 0);
}
/******************************************************************************/
/*!                               Structures                                  */

/* Structure that contains identifier details used in example */
struct identifier
{
    /* Variable to hold device address */
    uint8_t dev_addr;

    /* Variable that contains file descriptor */
    int8_t fd;
};

/****************************************************************************/
/*!                         Functions                                       */

/*!
 *  @brief Function that creates a mandatory delay required in some of the APIs.
 *
 * @param[in] period              : Delay in microseconds.
 * @param[in, out] intf_ptr       : Void pointer that can enable the linking of descriptors
 *                                  for interface related call backs
 *  @return void.
 *
 */
void user_delay_us(uint32_t period, void *intf_ptr){
    vTaskDelay(period / portTICK_PERIOD_MS);
}



/*!
 * @brief Function for print the temperature, humidity and pressure data.
 *
 * @param[out] comp_data    :   Structure instance of bme280_data
 *
 * @note Sensor data whose can be read
 *
 * sens_list
 * --------------
 * Pressure
 * Temperature
 * Humidity
 *
 */
void print_sensor_data(struct bme280_data *comp_data){
    ESP_LOGI(TAG_BME280, "Temperature: %.2f ºC", comp_data->temperature);
    ESP_LOGI(TAG_BME280, "Pressure: %.2f Pa", comp_data->pressure);
    ESP_LOGI(TAG_BME280, "Humidity: %.2f %%RH\n", comp_data->humidity);
}

/*!
 *  @brief Function for reading the sensor's registers through I2C bus.
 *
 *  @param[in] reg_addr       : Register address.
 *  @param[out] data          : Pointer to the data buffer to store the read data.
 *  @param[in] len            : No of bytes to read.
 *  @param[in, out] intf_ptr  : Void pointer that can enable the linking of descriptors
 *                                  for interface related call backs.
 *
 *  @return Status of execution
 *
 *  @retval 0 -> Success
 *  @retval > 0 -> Failure Info
 *
 */
int8_t user_i2c_read(uint8_t reg_addr, uint8_t *data, uint32_t len, void *intf_ptr){
    uint32_t iError = BME280_OK;
    esp_err_t err;
    struct identifier id;
    id = *((struct identifier *)intf_ptr);


    i2c_cmd_handle_t cmd = i2c_cmd_link_create();
    i2c_master_start(cmd);
    i2c_master_write_byte(cmd, (id.dev_addr << 1) | I2C_MASTER_WRITE, true);
    i2c_master_write_byte(cmd, reg_addr, true);

    i2c_master_start(cmd);
    i2c_master_write_byte(cmd, (id.dev_addr << 1) | I2C_MASTER_READ, true);

	if (len > 1) {
		i2c_master_read(cmd, data, len-1, I2C_MASTER_ACK);
	}
	i2c_master_read_byte(cmd, data + len - 1, I2C_MASTER_NACK);
	i2c_master_stop(cmd);    

	err = i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
	if (err == ESP_OK) {
		iError = ESP_OK;
	} else {
        ESP_LOGE(TAG_BME280, "I2C read failed, error=%d", err); // ESP_FAIL
		iError = FAIL;
	}

	i2c_cmd_link_delete(cmd);

	return (int8_t) iError;
}


/*!
 *  @brief Function for writing the sensor's registers through I2C bus.
 *
 *  @param[in] reg_addr       : Register address.
 *  @param[in] data           : Pointer to the data buffer whose value is to be written.
 *  @param[in] len            : No of bytes to write.
 *  @param[in, out] intf_ptr  : Void pointer that can enable the linking of descriptors
 *                                  for interface related call backs
 *
 *  @return Status of execution
 *
 *  @retval BME280_OK -> Success
 *  @retval BME280_E_COMM_FAIL -> Communication failure.
 *
 */
int8_t user_i2c_write(uint8_t reg_addr, const uint8_t *data, uint32_t len, void *intf_ptr){
    uint32_t iError = BME280_OK;
    esp_err_t err;
    struct identifier id;
    id = *((struct identifier *)intf_ptr);


    i2c_cmd_handle_t cmd = i2c_cmd_link_create();
    i2c_master_start(cmd);
    i2c_master_write_byte(cmd, (id.dev_addr << 1) | I2C_MASTER_WRITE, true);
    i2c_master_write_byte(cmd, reg_addr, true);

	i2c_master_write(cmd, data, len, true);
	i2c_master_stop(cmd);

	err = i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
	if (err == ESP_OK) {
		iError = BME280_OK;
	} else {
        ESP_LOGE(TAG_BME280, "I2C write failed, error=%d", err); // ESP_FAIL
		iError = BME280_E_COMM_FAIL;
	}
	i2c_cmd_link_delete(cmd);

	return (int8_t) iError;

}


/*!
 * @brief Function reads temperature, humidity and pressure data in forced mode.
 *
 * @param[in] dev   :   Structure instance of bme280_dev.
 *
 * @return Result of API execution status
 *
 * @retval BME280_OK - Success.
 * @retval BME280_E_NULL_PTR - Error: Null pointer error
 * @retval BME280_E_COMM_FAIL - Error: Communication fail error
 * @retval BME280_E_NVM_COPY_FAILED - Error: NVM copy failed
 *
 */
int8_t stream_sensor_data_forced_mode(struct bme280_dev *dev){
    /* Variable to define the result */
    int8_t rslt = BME280_OK;

    /* Variable to define the selecting sensors */
    uint8_t settings_sel = 0;

    /* Variable to store minimum wait time between consecutive measurement in force mode */
    uint32_t req_delay;

    /* Structure to get the pressure, temperature and humidity values */
    struct bme280_data comp_data;

    /* Recommended mode of operation: Indoor navigation */
    dev->settings.osr_h = BME280_OVERSAMPLING_1X;
    dev->settings.osr_p = BME280_OVERSAMPLING_16X;
    dev->settings.osr_t = BME280_OVERSAMPLING_2X;
    dev->settings.filter = BME280_FILTER_COEFF_16;

    settings_sel = BME280_OSR_PRESS_SEL | BME280_OSR_TEMP_SEL | BME280_OSR_HUM_SEL | BME280_FILTER_SEL;

    /* Set the sensor settings */
    rslt = bme280_set_sensor_settings(settings_sel, dev);
    if (rslt != BME280_OK)
    {
        ESP_LOGE(TAG_BME280, "Failed to set sensor settings (code %+d).", rslt);

        return rslt;
    }

    // printf("Temperature, Pressure, Humidity\n");

    /*Calculate the minimum delay required between consecutive measurement based upon the sensor enabled
     *  and the oversampling configuration. */
    req_delay = bme280_cal_meas_delay(&dev->settings);

    /* Continuously stream sensor data */
    while (1)
    {
        /* Set the sensor to forced mode */
        rslt = bme280_set_sensor_mode(BME280_FORCED_MODE, dev);
        if (rslt != BME280_OK)
        {
            fprintf(stderr, "Failed to set sensor mode (code %+d).", rslt);
            break;
        }

        /* Wait for the measurement to complete and print data */
        dev->delay_us(req_delay, dev->intf_ptr);
        rslt = bme280_get_sensor_data(BME280_ALL, &comp_data, dev);
        if (rslt != BME280_OK)
        {
            fprintf(stderr, "Failed to get sensor data (code %+d).", rslt);
            break;
        }

        print_sensor_data(&comp_data);
    }

    return rslt;    
}



uint8_t config_bme280(struct bme280_dev *dev){
    int8_t rslt;
    uint8_t settings_sel;

    dev->settings.osr_h = BME280_OVERSAMPLING_1X;
    dev->settings.osr_p = BME280_OVERSAMPLING_16X;
    dev->settings.osr_t = BME280_OVERSAMPLING_2X;
    dev->settings.filter = BME280_FILTER_COEFF_16;
    settings_sel = BME280_OSR_PRESS_SEL | BME280_OSR_TEMP_SEL | BME280_OSR_HUM_SEL | BME280_FILTER_SEL;
    rslt = bme280_set_sensor_settings(settings_sel, dev);
    if (rslt != BME280_OK)
    {
        ESP_LOGE(TAG_BME280, "Failed to set sensor settings (code %+d).", rslt);

        return rslt;
    }
    return BME280_OK;
}


void task_bme280_normal_mode(void *ignore)
{
    struct bme280_dev dev;

    struct identifier id;
    /* Variable to store minimum wait time between consecutive measurement in force mode */
    uint32_t req_delay;
    /* Structure to get the pressure, temperature and humidity values */
    struct bme280_data comp_data;

    /* Variable to define the result */
    int8_t rslt = BME280_OK;

    /* Make sure to select BME280_I2C_ADDR_PRIM or BME280_I2C_ADDR_SEC as needed */
    id.dev_addr = BME280_I2C_ADDR_PRIM;

    dev.intf = BME280_I2C_INTF;
    dev.read = user_i2c_read;
    dev.write = user_i2c_write;
    dev.delay_us = user_delay_us;

    /* Update interface pointer with the structure that contains both device address and file descriptor */
    dev.intf_ptr = &id;

    /* Initialize the bme280 */
    rslt = bme280_init(&dev);
    if (rslt == BME280_OK){
        ESP_LOGI(TAG_BME280, "BME280 init OK");
    } else {
        ESP_LOGE(TAG_BME280, "BME280 init failed. code: %d", rslt);
    }
    /* Configure the bme */
    rslt = config_bme280(&dev);
    if (rslt == BME280_OK){
        ESP_LOGI(TAG_BME280, "BME280 config OK");
        /*Calculate the minimum delay required between consecutive measurement based upon the sensor enabled
        *  and the oversampling configuration. */
        req_delay = bme280_cal_meas_delay(&dev.settings);

		while(true) {
			vTaskDelay(1000/portTICK_PERIOD_MS);
            /* Set the sensor to forced mode 
                Forced mode means that the sensor is in sleep modee, then a measurement is performed and the sensor is put 
                back to sleep mode.
            */
            rslt = bme280_set_sensor_mode(BME280_FORCED_MODE, &dev);
            if (rslt != BME280_OK)
            {
                ESP_LOGE(TAG_BME280, "Failed to set sensor mode (code %+d). Going out of task", rslt);
                break;
            }

            /* Wait for the measurement to complete and print data */
            dev.delay_us(req_delay, dev.intf_ptr);
            rslt = bme280_get_sensor_data(BME280_ALL, &comp_data, &dev);
            if (rslt != BME280_OK)
            {
                ESP_LOGE(TAG_BME280, "Failed to get sensor data (code %+d).", rslt);
                break;
            }

            print_sensor_data(&comp_data);
		}        
	} else {
		ESP_LOGE(TAG_BME280, "init or setting error. code: %d", rslt);
	}

	vTaskDelete(NULL);
}
// void task_bme280_normal_mode(void *ignore)
// {
// 	struct bme280_t bme280 = {
// 		.bus_write = BME280_I2C_bus_write,
// 		.bus_read = BME280_I2C_bus_read,
// 		.dev_addr = BME280_I2C_ADDRESS2,
// 		.delay_msec = BME280_delay_msek
// 	};

// 	s32 com_rslt;
// 	s32 v_uncomp_pressure_s32;
// 	s32 v_uncomp_temperature_s32;
// 	s32 v_uncomp_humidity_s32;

// 	com_rslt = bme280_init(&bme280);

// 	com_rslt += bme280_set_oversamp_pressure(BME280_OVERSAMP_16X);
// 	com_rslt += bme280_set_oversamp_temperature(BME280_OVERSAMP_2X);
// 	com_rslt += bme280_set_oversamp_humidity(BME280_OVERSAMP_1X);

// 	com_rslt += bme280_set_standby_durn(BME280_STANDBY_TIME_1_MS);
// 	com_rslt += bme280_set_filter(BME280_FILTER_COEFF_16);

// 	com_rslt += bme280_set_power_mode(BME280_NORMAL_MODE);
// 	if (com_rslt == SUCCESS) {
// 		while(true) {
// 			vTaskDelay(40/portTICK_PERIOD_MS);

// 			com_rslt = bme280_read_uncomp_pressure_temperature_humidity(
// 				&v_uncomp_pressure_s32, &v_uncomp_temperature_s32, &v_uncomp_humidity_s32);

// 			if (com_rslt == SUCCESS) {
// 				ESP_LOGI(TAG_BME280, "%.2f degC / %.3f hPa / %.3f %%",
// 					bme280_compensate_temperature_double(v_uncomp_temperature_s32),
// 					bme280_compensate_pressure_double(v_uncomp_pressure_s32)/100, // Pa -> hPa
// 					bme280_compensate_humidity_double(v_uncomp_humidity_s32));
// 			} else {
// 				ESP_LOGE(TAG_BME280, "measure error. code: %d", com_rslt);
// 			}
// 		}
// 	} else {
// 		ESP_LOGE(TAG_BME280, "init or setting error. code: %d", com_rslt);
// 	}

// 	vTaskDelete(NULL);
// }

// void task_bme280_forced_mode(void *ignore) {
// 	struct bme280_t bme280 = {
// 		.bus_write = BME280_I2C_bus_write,
// 		.bus_read = BME280_I2C_bus_read,
// 		.dev_addr = BME280_I2C_ADDRESS2,
// 		.delay_msec = BME280_delay_msek
// 	};

// 	s32 com_rslt;
// 	s32 v_uncomp_pressure_s32;
// 	s32 v_uncomp_temperature_s32;
// 	s32 v_uncomp_humidity_s32;

// 	com_rslt = bme280_init(&bme280);

// 	com_rslt += bme280_set_oversamp_pressure(BME280_OVERSAMP_1X);
// 	com_rslt += bme280_set_oversamp_temperature(BME280_OVERSAMP_1X);
// 	com_rslt += bme280_set_oversamp_humidity(BME280_OVERSAMP_1X);

// 	com_rslt += bme280_set_filter(BME280_FILTER_COEFF_OFF);
// 	if (com_rslt == SUCCESS) {
// 		while(true) {
// 			com_rslt = bme280_get_forced_uncomp_pressure_temperature_humidity(
// 				&v_uncomp_pressure_s32, &v_uncomp_temperature_s32, &v_uncomp_humidity_s32);

// 			if (com_rslt == SUCCESS) {
// 				ESP_LOGI(TAG_BME280, "%.2f degC / %.3f hPa / %.3f %%",
// 					bme280_compensate_temperature_double(v_uncomp_temperature_s32),
// 					bme280_compensate_pressure_double(v_uncomp_pressure_s32)/100, // Pa -> hPa
// 					bme280_compensate_humidity_double(v_uncomp_humidity_s32));
// 			} else {
// 				ESP_LOGE(TAG_BME280, "measure error. code: %d", com_rslt);
// 			}
// 		}
// 	} else {
// 		ESP_LOGE(TAG_BME280, "init or setting error. code: %d", com_rslt);
// 	}

// 	vTaskDelete(NULL);
// }

void app_main(void)
{
	i2c_master_init();
	xTaskCreate(&task_bme280_normal_mode, "bme280_normal_mode",  2048, NULL, 6, NULL);
	// xTaskCreate(&task_bme280_forced_mode, "bme280_forced_mode",  2048, NULL, 6, NULL);
}